# Generated by Django 4.1 on 2024-06-17 16:24

from django.db import migrations, models
import investments.models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="startup",
            name="growth_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=investments.models.random_growth_rate,
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="startup",
            name="interest",
            field=models.DecimalField(
                decimal_places=2,
                default=investments.models.random_interest,
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="date_invested",
            field=models.IntegerField(default=investments.models.calculate_date),
        ),
    ]
