# Generated by Django 4.2.11 on 2024-05-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='industry',
            field=models.TextField(default='Undefined'),
        ),
    ]
