# Generated by Django 4.2.11 on 2024-05-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_startup_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='profits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='startup',
            name='industry',
            field=models.TextField(),
        ),
    ]
