# Generated by Django 4.2.11 on 2024-05-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_investment_profits_alter_investment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='website_link',
            field=models.URLField(blank=True),
        ),
    ]
