# Generated by Django 4.2.11 on 2024-05-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_startup_website_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='website_link',
        ),
    ]
